FROM eclipse-temurin:17-jre-alpine
WORKDIR /opt/workdir

# Label to automatically link the package to the dataspot repository in GHCR
# This avoids the need to manually link the package after pushing
LABEL org.opencontainers.image.source=https://github.com/dcc-bs/dataspot
